from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

from giticizer.models import Commit, FileChange


def _load_mapping(mapping_file: Path) -> list[tuple[re.Pattern[str], str]]:
    rules = []
    for raw in mapping_file.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=>" not in line:
            continue
        pattern, group = [p.strip() for p in line.split("=>", 1)]
        rules.append((re.compile(pattern), group))
    return rules


def apply_group_mapping(commits: list[Commit], mapping_file: Path) -> list[Commit]:
    rules = _load_mapping(mapping_file)
    out = []
    for c in commits:
        files = []
        for fc in c.files:
            mapped = next((g for p, g in rules if p.search(fc.path)), fc.path)
            files.append(FileChange(path=mapped, added=fc.added, deleted=fc.deleted))
        out.append(
            Commit(rev=c.rev, author=c.author, date=c.date, message=c.message, files=tuple(files))
        )
    return out


def validate_group_mapping(repo: Path, mapping_file: Path) -> list[dict[str, object]]:
    rules = _load_mapping(mapping_file)
    paths = _repo_files(repo)
    matched = {p for p in paths if any(rx.search(p) for rx, _ in rules)}
    return [
        {"statistic": "rules", "value": len(rules)},
        {"statistic": "files-total", "value": len(paths)},
        {"statistic": "files-matched", "value": len(matched)},
        {"statistic": "files-unmatched", "value": len(paths) - len(matched)},
    ]


def generate_group_mapping(
    repo: Path,
    output_file: Path,
    *,
    depth: int = 2,
    min_files: int = 1,
) -> list[dict[str, object]]:
    if depth < 1:
        raise ValueError("depth must be >= 1")
    if min_files < 1:
        raise ValueError("min-files must be >= 1")

    files = _repo_files(repo)
    buckets: Counter[str] = Counter()
    for path in files:
        parts = path.split("/")
        key = "/".join(parts[:depth])
        if key:
            buckets[key] += 1

    rules: list[tuple[str, str, int]] = []
    for key, count in sorted(buckets.items()):
        if count < min_files:
            continue
        pattern = rf"^{re.escape(key)}/.*"
        group = key
        rules.append((pattern, group, count))

    lines = [
        "# Auto-generated by giticizer generate-mapping",
        f"# repo: {repo.resolve().as_posix()}",
        f"# depth: {depth}",
        f"# min-files: {min_files}",
        "",
    ]
    lines.extend(f"{pattern} => {group}" for pattern, group, _ in rules)
    output_file.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    return [
        {"statistic": "generated-rules", "value": len(rules)},
        {"statistic": "source-files", "value": len(files)},
        {"statistic": "output-file", "value": output_file.as_posix()},
    ]


def _repo_files(repo: Path) -> list[str]:
    return [
        p.relative_to(repo).as_posix()
        for p in repo.rglob("*")
        if p.is_file() and "/.git/" not in f"/{p.relative_to(repo).as_posix()}"
    ]
